// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'2df7434fda6dbfaa3c04d9dc93707b8151594f1794993299aa63e23f46d969f6'>;
export type ExecutionHash =
  ExecutionHashBase<'cf7053f49b1b78dfcd058027332948dfe97d59697e5773c954afdd741a2e0b0b'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Address: {
      readonly building_number: CodecTypes['pg/text@1']['output'];
      readonly city: CodecTypes['pg/text@1']['output'];
      readonly country: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly lat: CodecTypes['pg/float8@1']['output'] | null;
      readonly lng: CodecTypes['pg/float8@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly postalCode: CodecTypes['pg/text@1']['output'];
      readonly street: CodecTypes['pg/text@1']['output'];
      readonly type: CodecTypes['pg/int4@1']['output'];
      readonly unit_number: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
    readonly Daycare: {
      readonly building_number: CodecTypes['pg/text@1']['output'];
      readonly city: CodecTypes['pg/text@1']['output'];
      readonly closing_hours: CodecTypes['pg/time-temporal@1']['output'];
      readonly country: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly lat: CodecTypes['pg/float8@1']['output'] | null;
      readonly lng: CodecTypes['pg/float8@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly opening_hours: CodecTypes['pg/time-temporal@1']['output'];
      readonly postalCode: CodecTypes['pg/text@1']['output'];
      readonly street: CodecTypes['pg/text@1']['output'];
      readonly unit_number: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Institution: {
      readonly building_number: CodecTypes['pg/text@1']['output'];
      readonly city: CodecTypes['pg/text@1']['output'];
      readonly closing_hours: CodecTypes['pg/time-temporal@1']['output'];
      readonly country: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly lat: CodecTypes['pg/float8@1']['output'] | null;
      readonly lng: CodecTypes['pg/float8@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly opening_hours: CodecTypes['pg/time-temporal@1']['output'];
      readonly postalCode: CodecTypes['pg/text@1']['output'];
      readonly street: CodecTypes['pg/text@1']['output'];
      readonly type: CodecTypes['pg/int4@1']['output'];
      readonly unit_number: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Nanny: {
      readonly availability: CodecTypes['pg/bool@1']['output'];
      readonly hourly_wage: CodecTypes['pg/float8@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly phone_number: CodecTypes['pg/text@1']['output'];
      readonly rating: CodecTypes['pg/float8@1']['output'] | null;
      readonly rating_count: CodecTypes['pg/int4@1']['output'] | null;
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
    readonly User: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly password_hash: CodecTypes['pg/text@1']['output'];
      readonly surname: CodecTypes['pg/text@1']['output'];
      readonly type: CodecTypes['pg/int4@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Address: {
      readonly building_number: CodecTypes['pg/text@1']['input'];
      readonly city: CodecTypes['pg/text@1']['input'];
      readonly country: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly lat: CodecTypes['pg/float8@1']['input'] | null;
      readonly lng: CodecTypes['pg/float8@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly postalCode: CodecTypes['pg/text@1']['input'];
      readonly street: CodecTypes['pg/text@1']['input'];
      readonly type: CodecTypes['pg/int4@1']['input'];
      readonly unit_number: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
    readonly Daycare: {
      readonly building_number: CodecTypes['pg/text@1']['input'];
      readonly city: CodecTypes['pg/text@1']['input'];
      readonly closing_hours: CodecTypes['pg/time-temporal@1']['input'];
      readonly country: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly lat: CodecTypes['pg/float8@1']['input'] | null;
      readonly lng: CodecTypes['pg/float8@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly opening_hours: CodecTypes['pg/time-temporal@1']['input'];
      readonly postalCode: CodecTypes['pg/text@1']['input'];
      readonly street: CodecTypes['pg/text@1']['input'];
      readonly unit_number: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Institution: {
      readonly building_number: CodecTypes['pg/text@1']['input'];
      readonly city: CodecTypes['pg/text@1']['input'];
      readonly closing_hours: CodecTypes['pg/time-temporal@1']['input'];
      readonly country: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly lat: CodecTypes['pg/float8@1']['input'] | null;
      readonly lng: CodecTypes['pg/float8@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly opening_hours: CodecTypes['pg/time-temporal@1']['input'];
      readonly postalCode: CodecTypes['pg/text@1']['input'];
      readonly street: CodecTypes['pg/text@1']['input'];
      readonly type: CodecTypes['pg/int4@1']['input'];
      readonly unit_number: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Nanny: {
      readonly availability: CodecTypes['pg/bool@1']['input'];
      readonly hourly_wage: CodecTypes['pg/float8@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly phone_number: CodecTypes['pg/text@1']['input'];
      readonly rating: CodecTypes['pg/float8@1']['input'] | null;
      readonly rating_count: CodecTypes['pg/int4@1']['input'] | null;
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
    readonly User: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly password_hash: CodecTypes['pg/text@1']['input'];
      readonly surname: CodecTypes['pg/text@1']['input'];
      readonly type: CodecTypes['pg/int4@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly address: {
      readonly building_number: CodecTypes['pg/text@1']['output'];
      readonly city: CodecTypes['pg/text@1']['output'];
      readonly country: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly lat: CodecTypes['pg/float8@1']['output'] | null;
      readonly lng: CodecTypes['pg/float8@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly postalCode: CodecTypes['pg/text@1']['output'];
      readonly street: CodecTypes['pg/text@1']['output'];
      readonly type: CodecTypes['pg/int4@1']['output'];
      readonly unit_number: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
    readonly daycare: {
      readonly building_number: CodecTypes['pg/text@1']['output'];
      readonly city: CodecTypes['pg/text@1']['output'];
      readonly closing_hours: CodecTypes['pg/time-temporal@1']['output'];
      readonly country: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly lat: CodecTypes['pg/float8@1']['output'] | null;
      readonly lng: CodecTypes['pg/float8@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly opening_hours: CodecTypes['pg/time-temporal@1']['output'];
      readonly postalCode: CodecTypes['pg/text@1']['output'];
      readonly street: CodecTypes['pg/text@1']['output'];
      readonly unit_number: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly institution: {
      readonly building_number: CodecTypes['pg/text@1']['output'];
      readonly city: CodecTypes['pg/text@1']['output'];
      readonly closing_hours: CodecTypes['pg/time-temporal@1']['output'];
      readonly country: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly lat: CodecTypes['pg/float8@1']['output'] | null;
      readonly lng: CodecTypes['pg/float8@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly opening_hours: CodecTypes['pg/time-temporal@1']['output'];
      readonly postalCode: CodecTypes['pg/text@1']['output'];
      readonly street: CodecTypes['pg/text@1']['output'];
      readonly type: CodecTypes['pg/int4@1']['output'];
      readonly unit_number: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly nanny: {
      readonly availability: CodecTypes['pg/bool@1']['output'];
      readonly hourly_wage: CodecTypes['pg/float8@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly phone_number: CodecTypes['pg/text@1']['output'];
      readonly rating: CodecTypes['pg/float8@1']['output'] | null;
      readonly rating_count: CodecTypes['pg/int4@1']['output'] | null;
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
    readonly user: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly password_hash: CodecTypes['pg/text@1']['output'];
      readonly surname: CodecTypes['pg/text@1']['output'];
      readonly type: CodecTypes['pg/int4@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly address: {
      readonly building_number: CodecTypes['pg/text@1']['input'];
      readonly city: CodecTypes['pg/text@1']['input'];
      readonly country: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly lat: CodecTypes['pg/float8@1']['input'] | null;
      readonly lng: CodecTypes['pg/float8@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly postalCode: CodecTypes['pg/text@1']['input'];
      readonly street: CodecTypes['pg/text@1']['input'];
      readonly type: CodecTypes['pg/int4@1']['input'];
      readonly unit_number: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
    readonly daycare: {
      readonly building_number: CodecTypes['pg/text@1']['input'];
      readonly city: CodecTypes['pg/text@1']['input'];
      readonly closing_hours: CodecTypes['pg/time-temporal@1']['input'];
      readonly country: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly lat: CodecTypes['pg/float8@1']['input'] | null;
      readonly lng: CodecTypes['pg/float8@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly opening_hours: CodecTypes['pg/time-temporal@1']['input'];
      readonly postalCode: CodecTypes['pg/text@1']['input'];
      readonly street: CodecTypes['pg/text@1']['input'];
      readonly unit_number: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly institution: {
      readonly building_number: CodecTypes['pg/text@1']['input'];
      readonly city: CodecTypes['pg/text@1']['input'];
      readonly closing_hours: CodecTypes['pg/time-temporal@1']['input'];
      readonly country: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly lat: CodecTypes['pg/float8@1']['input'] | null;
      readonly lng: CodecTypes['pg/float8@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly opening_hours: CodecTypes['pg/time-temporal@1']['input'];
      readonly postalCode: CodecTypes['pg/text@1']['input'];
      readonly street: CodecTypes['pg/text@1']['input'];
      readonly type: CodecTypes['pg/int4@1']['input'];
      readonly unit_number: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly nanny: {
      readonly availability: CodecTypes['pg/bool@1']['input'];
      readonly hourly_wage: CodecTypes['pg/float8@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly phone_number: CodecTypes['pg/text@1']['input'];
      readonly rating: CodecTypes['pg/float8@1']['input'] | null;
      readonly rating_count: CodecTypes['pg/int4@1']['input'] | null;
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
    readonly user: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly password_hash: CodecTypes['pg/text@1']['input'];
      readonly surname: CodecTypes['pg/text@1']['input'];
      readonly type: CodecTypes['pg/int4@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Address = {
    building_number: CodecTypes['pg/text@1']['output'];
    city: CodecTypes['pg/text@1']['output'];
    country: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    lat: CodecTypes['pg/float8@1']['output'] | null;
    lng: CodecTypes['pg/float8@1']['output'] | null;
    name: CodecTypes['pg/text@1']['output'];
    postalCode: CodecTypes['pg/text@1']['output'];
    street: CodecTypes['pg/text@1']['output'];
    type: CodecTypes['pg/int4@1']['output'];
    unit_number: CodecTypes['pg/text@1']['output'] | null;
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    userId: CodecTypes['pg/text@1']['output'];
    user: public_User;
    readonly [RelationKeys]?: 'user';
  };
  export type public_Daycare = {
    building_number: CodecTypes['pg/text@1']['output'];
    city: CodecTypes['pg/text@1']['output'];
    closing_hours: CodecTypes['pg/time-temporal@1']['output'];
    country: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    lat: CodecTypes['pg/float8@1']['output'] | null;
    lng: CodecTypes['pg/float8@1']['output'] | null;
    name: CodecTypes['pg/text@1']['output'];
    opening_hours: CodecTypes['pg/time-temporal@1']['output'];
    postalCode: CodecTypes['pg/text@1']['output'];
    street: CodecTypes['pg/text@1']['output'];
    unit_number: CodecTypes['pg/text@1']['output'] | null;
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_Institution = {
    building_number: CodecTypes['pg/text@1']['output'];
    city: CodecTypes['pg/text@1']['output'];
    closing_hours: CodecTypes['pg/time-temporal@1']['output'];
    country: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    lat: CodecTypes['pg/float8@1']['output'] | null;
    lng: CodecTypes['pg/float8@1']['output'] | null;
    name: CodecTypes['pg/text@1']['output'];
    opening_hours: CodecTypes['pg/time-temporal@1']['output'];
    postalCode: CodecTypes['pg/text@1']['output'];
    street: CodecTypes['pg/text@1']['output'];
    type: CodecTypes['pg/int4@1']['output'];
    unit_number: CodecTypes['pg/text@1']['output'] | null;
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_Nanny = {
    availability: CodecTypes['pg/bool@1']['output'];
    hourly_wage: CodecTypes['pg/float8@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    phone_number: CodecTypes['pg/text@1']['output'];
    rating: CodecTypes['pg/float8@1']['output'] | null;
    rating_count: CodecTypes['pg/int4@1']['output'] | null;
    userId: CodecTypes['pg/text@1']['output'];
    user: public_User;
    readonly [RelationKeys]?: 'user';
  };
  export type public_User = {
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    password_hash: CodecTypes['pg/text@1']['output'];
    surname: CodecTypes['pg/text@1']['output'];
    type: CodecTypes['pg/int4@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    addresses: public_Address[];
    nannies: public_Nanny[];
    readonly [RelationKeys]?: 'addresses' | 'nannies';
  };
}

export declare const models: {
  public: {
    Address: Models.public_Address;
    Daycare: Models.public_Daycare;
    Institution: Models.public_Institution;
    Nanny: Models.public_Nanny;
    User: Models.public_User;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly address: {
              columns: {
                readonly building_number: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly city: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly country: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly lat: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly lng: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly postalCode: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly street: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly type: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly unit_number: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly userId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'address_userId_idx_a489d58a';
                  readonly prefix: 'address_userId_idx';
                  readonly columns: readonly ['userId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'address';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly daycare: {
              columns: {
                readonly building_number: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly city: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly closing_hours: {
                  readonly nativeType: 'time';
                  readonly codecId: 'pg/time-temporal@1';
                  readonly nullable: false;
                };
                readonly country: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly lat: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly lng: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly opening_hours: {
                  readonly nativeType: 'time';
                  readonly codecId: 'pg/time-temporal@1';
                  readonly nullable: false;
                };
                readonly postalCode: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly street: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly unit_number: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly institution: {
              columns: {
                readonly building_number: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly city: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly closing_hours: {
                  readonly nativeType: 'time';
                  readonly codecId: 'pg/time-temporal@1';
                  readonly nullable: false;
                };
                readonly country: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly lat: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly lng: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly opening_hours: {
                  readonly nativeType: 'time';
                  readonly codecId: 'pg/time-temporal@1';
                  readonly nullable: false;
                };
                readonly postalCode: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly street: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly type: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly unit_number: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly nanny: {
              columns: {
                readonly availability: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly hourly_wage: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/float8@1', 0>;
                  };
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly phone_number: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly rating: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/float8@1', 0>;
                  };
                };
                readonly rating_count: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly userId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['userId'] }];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'nanny';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly user: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly password_hash: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly surname: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly type: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly Type: {
              readonly kind: 'valueSet';
              readonly values: readonly ['MOM', 'NANNY'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly address: { readonly namespace: 'public' & NamespaceId; readonly model: 'Address' };
    readonly daycare: { readonly namespace: 'public' & NamespaceId; readonly model: 'Daycare' };
    readonly institution: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Institution';
    };
    readonly nanny: { readonly namespace: 'public' & NamespaceId; readonly model: 'Nanny' };
    readonly user: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Address: {
            readonly fields: {
              readonly building_number: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly city: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly country: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly lat: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly lng: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly postalCode: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly street: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly unit_number: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'address';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly building_number: { readonly column: 'building_number' };
                readonly city: { readonly column: 'city' };
                readonly country: { readonly column: 'country' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly id: { readonly column: 'id' };
                readonly lat: { readonly column: 'lat' };
                readonly lng: { readonly column: 'lng' };
                readonly name: { readonly column: 'name' };
                readonly postalCode: { readonly column: 'postalCode' };
                readonly street: { readonly column: 'street' };
                readonly type: { readonly column: 'type' };
                readonly unit_number: { readonly column: 'unit_number' };
                readonly updatedAt: { readonly column: 'updatedAt' };
                readonly userId: { readonly column: 'userId' };
              };
            };
          };
          readonly Daycare: {
            readonly fields: {
              readonly building_number: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly city: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly closing_hours: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/time-temporal@1' };
              };
              readonly country: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly lat: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly lng: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly opening_hours: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/time-temporal@1' };
              };
              readonly postalCode: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly street: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly unit_number: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'daycare';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly building_number: { readonly column: 'building_number' };
                readonly city: { readonly column: 'city' };
                readonly closing_hours: { readonly column: 'closing_hours' };
                readonly country: { readonly column: 'country' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly id: { readonly column: 'id' };
                readonly lat: { readonly column: 'lat' };
                readonly lng: { readonly column: 'lng' };
                readonly name: { readonly column: 'name' };
                readonly opening_hours: { readonly column: 'opening_hours' };
                readonly postalCode: { readonly column: 'postalCode' };
                readonly street: { readonly column: 'street' };
                readonly unit_number: { readonly column: 'unit_number' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Institution: {
            readonly fields: {
              readonly building_number: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly city: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly closing_hours: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/time-temporal@1' };
              };
              readonly country: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly lat: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly lng: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly opening_hours: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/time-temporal@1' };
              };
              readonly postalCode: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly street: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly unit_number: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'institution';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly building_number: { readonly column: 'building_number' };
                readonly city: { readonly column: 'city' };
                readonly closing_hours: { readonly column: 'closing_hours' };
                readonly country: { readonly column: 'country' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly id: { readonly column: 'id' };
                readonly lat: { readonly column: 'lat' };
                readonly lng: { readonly column: 'lng' };
                readonly name: { readonly column: 'name' };
                readonly opening_hours: { readonly column: 'opening_hours' };
                readonly postalCode: { readonly column: 'postalCode' };
                readonly street: { readonly column: 'street' };
                readonly type: { readonly column: 'type' };
                readonly unit_number: { readonly column: 'unit_number' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Nanny: {
            readonly fields: {
              readonly availability: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly hourly_wage: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly phone_number: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly rating: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly rating_count: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'nanny';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly availability: { readonly column: 'availability' };
                readonly hourly_wage: { readonly column: 'hourly_wage' };
                readonly id: { readonly column: 'id' };
                readonly phone_number: { readonly column: 'phone_number' };
                readonly rating: { readonly column: 'rating' };
                readonly rating_count: { readonly column: 'rating_count' };
                readonly userId: { readonly column: 'userId' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly password_hash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly surname: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly addresses: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Address';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly nannies: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Nanny';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'user';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'createdAt' };
                readonly email: { readonly column: 'email' };
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly password_hash: { readonly column: 'password_hash' };
                readonly surname: { readonly column: 'surname' };
                readonly type: { readonly column: 'type' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
        };
        readonly enum: {
          readonly Type: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'MOM'; readonly value: 'MOM' },
              { readonly name: 'NANNY'; readonly value: 'NANNY' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'address';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'daycare';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'institution';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'nanny';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'user';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
